apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }} # Send traffic to pods with this label

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.targetPort }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config"

          env:
            - name: ENV_SYNC_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secret"
                  key: ENV_SYNC_SECRET
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          livenessProbe: # failure allows kubernetes to restart the pod
            httpGet:
              path: /health/live
              port: {{ .Values.config.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe: # failure allows kubernetes to remove pod from load balancer
            httpGet:
              path: /health/ready
              port: {{ .Values.config.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 2 # After 2 failures, the pod is considered not ready
