apiVersion: v1
kind: Service
metadata:
  name: { { .Release.Name } }
  namespace: { { .Release.Namespace } }
spec:
  type: ClusterIP # Internal only - not accessible from outside
  selector:
    app: { { .Release.Name } } # Send traffic to pods with this label (matches our deployment label)
  ports:
    - port: 80 # Port the service listens on (inside the cluster)
      targetPort: { { .Values.config.targetPort } } # Port the container is running on
