apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envsync-ingress
  namespace: envsync
spec:
  ingressClassName: nginx # Use the nginx ingress controller that we enabled in minikube
  rules:
    - host: envsync.local # We'll map this to minikube's IP address in /etc/hosts
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: envsync-backend # The service we created in the service.yml file
                port:
                  number: 80 # The service port (not the container port)
